# Runs R CMD CHECK on the package.
name: call-r-cmd-check

on:
  push:
    paths-ignore:
      - .devcontainer
      - .github
      - '.gitignore'
      - '.Rbuildignore'
      - 'CONTRIBUTING.md'
      - 'LICENSE'
      - 'README.md'
  workflow_dispatch:

# Cancel active CI runs for a PR before starting another run
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call-workflow:
    uses: nmfs-ost/ghactions4r/.github/workflows/r-cmd-check.yml@main
    with: 
      gha_timeout_minutes: 60
      
