# Runs devtools::document() and styler::style_active_package(), then opens a
# pull request to the branch that had changes in the push that triggered the
# workflow.
name: call-doc-and-style-r

on:
  push:
    branches:
      - dev 
      - main
  workflow_dispatch:

# Cancel active CI runs for a PR before starting another run
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call-workflow:
    uses: nmfs-ost/ghactions4r/.github/workflows/doc-and-style-r.yml@main
    secrets:
      PAT: ${{ secrets.PAT }}
