# Runs devtools::spell_check().
name: call-spell-check

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  cspell:
    uses: noaa-fims/.github/.github/workflows/cspell.yml@main
